services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: techshop
      MYSQL_ROOT_PASSWORD: Jatin@1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Backend/App:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=techshop
      - DB_USER=root
      - DB_PASSWORD=Jatin@1234
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: