# Generated by Django 5.2.7 on 2026-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_vendorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedkit",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
