# Generated by Django 5.2.7 on 2026-03-29 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_projectreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="stock",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="offer",
            name="vendor_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="vendor_type",
            field=models.CharField(
                choices=[("ONLINE", "Online Platform"), ("LOCAL", "Local Partner")],
                default="ONLINE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="website_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="delivery_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="offer",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="offer",
            name="url",
            field=models.URLField(default="https://techshopway.com"),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
