# Generated by Django 5.2.7 on 2026-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_vendorprofile_description_vendorprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="address",
            field=models.TextField(
                blank=True, help_text="Full street address", null=True
            ),
        ),
    ]
